name: CI

on: [push, pull_request]

jobs:
  install_dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: intl
          tools: composer:v2
          coverage: none
      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Run composer install
        run: composer install -n --prefer-dist

  phpunit:
    runs-on: ubuntu-latest
    needs: [install_dependencies]
    steps:
      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Run PHPUnit
        run: vendor/bin/phpunit
  phpstan:
    runs-on: ubuntu-latest
    needs: [install_dependencies]
    steps:
      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Run PHPStan
        run: vendor/bin/phpstan analyse --error-format=github
  php-cs-fixer:
    runs-on: ubuntu-latest
    needs: [install_dependencies]
    steps:
      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Run php-cs-fixer
        run: vendor/bin/php-cs-fixer fix --diff --dry-run
  rector:
    runs-on: ubuntu-latest
    needs: [install_dependencies]
    steps:
      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Run rector
        run: vendor/bin/rector process --dry-run